<a href="https://colab.research.google.com/github/rubensrudio/Pytorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# LISTS

In [3]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [4]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NUMPY ARRAYS

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.52460282, 0.10909845, 0.57368773, 0.42722632],
       [0.77571404, 0.91401553, 0.64973455, 0.26653323],
       [0.89408242, 0.92448808, 0.37020511, 0.865071  ]])

In [8]:
np1.dtype

dtype('float64')

# TENSORS

In [17]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.9556,  0.7065, -0.2500, -1.7720],
        [ 0.4174,  0.2870, -0.8898,  0.7040],
        [-0.1472,  0.9708,  1.1331,  0.8963]])

In [12]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5246, 0.1091, 0.5737, 0.4272],
        [0.7757, 0.9140, 0.6497, 0.2665],
        [0.8941, 0.9245, 0.3702, 0.8651]], dtype=torch.float64)